/**
 * wiring / gacha-editor-dialog-wiring.ts — 抽卡物品编辑弹窗装配簇（从 index.ts 迁出，x4-ab）。
 */
import { createShowGachaItemEditorDialog } from '../features/gacha/gacha-item-editor-dialog';
import { STORAGE_KEY_GACHA_POOL_SETTINGS } from '../shared/storage-keys';

export function createGachaEditorDialogWiring(deps: any) {
  const { GACHA_CUSTOM_FIELD_KEY_MAX_LENGTH, GACHA_CUSTOM_FIELD_MAX_COUNT, GACHA_CUSTOM_FIELD_RESERVED_KEYS, GACHA_CUSTOM_FIELD_VALUE_MAX_LENGTH, GACHA_EFFECT_FIELD_ALIASES, GACHA_TAG_FIELD_ALIASES, GACHA_TARGET_COLUMN_KEYS, GACHA_TARGET_COLUMN_LABELS, GACHA_TARGET_COLUMN_VALUE_MAX_LENGTH, GACHA_TARGET_TABLE_MAX_LENGTH, bindTutorialButtonsIn, buildDefaultGachaPoolDefinition, buildGachaCustomFieldHeaderMap, buildStableGachaCustomItemId, cachedRawData_ACC, collectGachaLocalStorageSnapshot, countUnicodeCharacters, createUniqueGachaItemId, ensureGachaCatalogLoaded, ensureGachaPoolsForTags, escapeHtml, gachaCatalogCache_ACC, gachaCatalogLoadTask_ACC, gachaShopUiRefreshTimer_ACC, getAllGachaItemDefinitions, getAllGachaPoolConfigDefinitions, getConfig, getCore, getCustomGachaItemDefinitions, getGachaCustomFieldEntries, getGachaItemCustomTableNameIconContext, getGachaItemDefinitionFingerprint, getGachaNamedCustomField, getGachaReservedCustomFieldHeaders, getGachaRewardFieldLimits, getGachaShopProgressContainers, getJsonLikeErrorMessage, getRuntimeErrorMessage, getTableData, getTutorialButtonHtml, hydrateCustomTableNameIconsIn, inferEquipmentTableTypeForGachaItem, isGachaFieldAlias, isGachaItemEnabled, normalizeGachaCustomFields, normalizeGachaRewardTarget, normalizeGachaTargetColumns, normalizeGachaTargetTable, parseEquipmentItems, parseInventoryItems, refreshGachaShardShop, refreshGachaVisualization, renderGachaItemIconContent, restoreGachaLocalStorageSnapshot, runInSaveQueue, saveStoredGachaCatalog, setupOverlayClose, showGachaPoolNameDialog, showGachaSettingsDialog, startGachaShopUiRefresh, truncateGachaText, validateGachaCatalogImportItemTarget, validateGachaCustomFieldsForTargetTable } = deps;
  const showGachaItemEditorDialog = createShowGachaItemEditorDialog({
    bindTutorialButtonsIn: (...a: any[]) => bindTutorialButtonsIn(...a),
    buildDefaultGachaPoolDefinition: (...a: any[]) => buildDefaultGachaPoolDefinition(...a),
    buildGachaCustomFieldHeaderMap: (...a: any[]) => buildGachaCustomFieldHeaderMap(...a),
    buildStableGachaCustomItemId: (...a: any[]) => buildStableGachaCustomItemId(...a),
    collectGachaLocalStorageSnapshot: (...a: any[]) => collectGachaLocalStorageSnapshot(...a),
    countUnicodeCharacters: (...a: any[]) => countUnicodeCharacters(...a),
    createUniqueGachaItemId: (...a: any[]) => createUniqueGachaItemId(...a),
    ensureGachaCatalogLoaded: (...a: any[]) => ensureGachaCatalogLoaded(...a),
    ensureGachaPoolsForTags: (...a: any[]) => ensureGachaPoolsForTags(...a),
    getAllGachaItemDefinitions: (...a: any[]) => getAllGachaItemDefinitions(...a),
    getAllGachaPoolConfigDefinitions: (...a: any[]) => getAllGachaPoolConfigDefinitions(...a),
    getConfig: (...a: any[]) => getConfig(...a),
    getCore: (...a: any[]) => getCore(...a),
    getCustomGachaItemDefinitions: (...a: any[]) => getCustomGachaItemDefinitions(...a),
    getGachaCustomFieldEntries: (...a: any[]) => getGachaCustomFieldEntries(...a),
    getGachaItemCustomTableNameIconContext: (...a: any[]) => getGachaItemCustomTableNameIconContext(...a),
    getGachaItemDefinitionFingerprint: (...a: any[]) => getGachaItemDefinitionFingerprint(...a),
    getGachaNamedCustomField: (...a: any[]) => getGachaNamedCustomField(...a),
    getGachaReservedCustomFieldHeaders: (...a: any[]) => getGachaReservedCustomFieldHeaders(...a),
    getGachaRewardFieldLimits: (...a: any[]) => getGachaRewardFieldLimits(...a),
    getGachaShopProgressContainers: (...a: any[]) => getGachaShopProgressContainers(...a),
    getJsonLikeErrorMessage: (...a: any[]) => getJsonLikeErrorMessage(...a),
    getRuntimeErrorMessage: (...a: any[]) => getRuntimeErrorMessage(...a),
    getTableData: (...a: any[]) => getTableData(...a),
    getTutorialButtonHtml: (...a: any[]) => getTutorialButtonHtml(...a),
    hydrateCustomTableNameIconsIn: (...a: any[]) => hydrateCustomTableNameIconsIn(...a),
    inferEquipmentTableTypeForGachaItem: (...a: any[]) => inferEquipmentTableTypeForGachaItem(...a),
    isGachaFieldAlias: (...a: any[]) => isGachaFieldAlias(...a),
    isGachaItemEnabled: (...a: any[]) => isGachaItemEnabled(...a),
    normalizeGachaCustomFields: (...a: any[]) => normalizeGachaCustomFields(...a),
    normalizeGachaRewardTarget: (...a: any[]) => normalizeGachaRewardTarget(...a),
    normalizeGachaTargetColumns: (...a: any[]) => normalizeGachaTargetColumns(...a),
    normalizeGachaTargetTable: (...a: any[]) => normalizeGachaTargetTable(...a),
    parseEquipmentItems: (...a: any[]) => parseEquipmentItems(...a),
    parseInventoryItems: (...a: any[]) => parseInventoryItems(...a),
    refreshGachaShardShop: (...a: any[]) => refreshGachaShardShop(...a),
    refreshGachaVisualization: (...a: any[]) => refreshGachaVisualization(...a),
    renderGachaItemIconContent: (...a: any[]) => renderGachaItemIconContent(...a),
    restoreGachaLocalStorageSnapshot: (...a: any[]) => restoreGachaLocalStorageSnapshot(...a),
    runInSaveQueue: (...a: any[]) => runInSaveQueue(...a),
    saveStoredGachaCatalog: (...a: any[]) => saveStoredGachaCatalog(...a),
    setupOverlayClose: (...a: any[]) => setupOverlayClose(...a),
    showGachaPoolNameDialog: (...a: any[]) => showGachaPoolNameDialog(...a),
    showGachaSettingsDialog: (...a: any[]) => showGachaSettingsDialog(...a),
    startGachaShopUiRefresh: (...a: any[]) => startGachaShopUiRefresh(...a),
    truncateGachaText: (...a: any[]) => truncateGachaText(...a),
    validateGachaCatalogImportItemTarget: (...a: any[]) => validateGachaCatalogImportItemTarget(...a),
    validateGachaCustomFieldsForTargetTable: (...a: any[]) => validateGachaCustomFieldsForTargetTable(...a),
    escapeHtml: (...a: any[]) => escapeHtml(...a),
    GACHA_CUSTOM_FIELD_KEY_MAX_LENGTH: GACHA_CUSTOM_FIELD_KEY_MAX_LENGTH,
    GACHA_CUSTOM_FIELD_MAX_COUNT: GACHA_CUSTOM_FIELD_MAX_COUNT,
    GACHA_CUSTOM_FIELD_RESERVED_KEYS: GACHA_CUSTOM_FIELD_RESERVED_KEYS,
    GACHA_CUSTOM_FIELD_VALUE_MAX_LENGTH: GACHA_CUSTOM_FIELD_VALUE_MAX_LENGTH,
    GACHA_EFFECT_FIELD_ALIASES: GACHA_EFFECT_FIELD_ALIASES,
    GACHA_TAG_FIELD_ALIASES: GACHA_TAG_FIELD_ALIASES,
    GACHA_TARGET_COLUMN_KEYS: GACHA_TARGET_COLUMN_KEYS,
    GACHA_TARGET_COLUMN_LABELS: GACHA_TARGET_COLUMN_LABELS,
    GACHA_TARGET_COLUMN_VALUE_MAX_LENGTH: GACHA_TARGET_COLUMN_VALUE_MAX_LENGTH,
    GACHA_TARGET_TABLE_MAX_LENGTH: GACHA_TARGET_TABLE_MAX_LENGTH,
    STORAGE_KEY_GACHA_POOL_SETTINGS: STORAGE_KEY_GACHA_POOL_SETTINGS,
    getCachedRawData: () => cachedRawData_ACC.v,
    getGachaCatalogCache: () => gachaCatalogCache_ACC.v,
    setGachaCatalogCache: (v: any) => { gachaCatalogCache_ACC.v = v; },
    getGachaCatalogLoadTask: () => gachaCatalogLoadTask_ACC.v,
    setGachaCatalogLoadTask: (v: any) => { gachaCatalogLoadTask_ACC.v = v; },
      getGachaShopUiRefreshTimer: () => gachaShopUiRefreshTimer_ACC.v,
    setGachaShopUiRefreshTimer: (v: any) => { gachaShopUiRefreshTimer_ACC.v = v; },
});
  return { showGachaItemEditorDialog };
}
